name: flutter_timezone_observer
description: >
  Get and observe the device's IANA timezone. Includes mixins to automatically sync the timezone when the app resumes.
version: 1.0.0
homepage: https://github.com/kalaganov/flutter_timezone_observer
repository: https://github.com/kalaganov/flutter_timezone_observer
issue_tracker: https://github.com/kalaganov/flutter_timezone_observer/issues
topics:
  - timezone
  - zone
  - time
  - observer
  - native

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  coverage: ^1.15.0
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter_timezone_observer
        pluginClass: FlutterTimezoneObserverPlugin
      ios:
        pluginClass: FlutterTimezoneObserverPlugin

